# https://github.com/KrauseFx/fastlane/tree/master/docs

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.26.0"

before_all do |lane|
end

lane :prebuild do
  
  # if you're not me, you need to inject your own GitHub etc app API keys.
  # but don't worry, those are only needed if you'll be using OAuth to authenticate
  # with services, not if you're using e.g. personal token from GitHub.
  # you can register your own app at https://github.com/settings/applications/new

  # if this is running on CI, just inject dummy keys - they're not used in tests at all.
  if ENV["XCS"] == "1"
    puts "Running on XCS, injecting dummy credentials"

  end

  # cocoapods
end

lane :test do
  run_tests
end

private_lane :run_tests do
  prebuild
  xcodebuild(
    test: true,
    scheme: 'Buildasaur',
    workspace: 'Buildasaur.xcworkspace'
    )
end

lane :release do
  run_tests
  build
  release_no_build
end

lane :release_no_build do
  raise "No built app found" unless File.exist?("../build/Buildasaur.app")
  version = get_info_plist_value(
    key: "CFBundleShortVersionString",
    path: "Buildasaur/Info.plist"
  )
  github(
    assets: ["./build/Buildasaur.app"],
    version: version
    )
end

lane :build do
  gym(
    scheme: 'Buildasaur',
    output_name: 'Buildasaur',
    output_directory: './build'
    )
end

private_lane :github do |params|

  assets = params[:assets]
  version = params[:version]
  version_tag = "v#{version}"

  # prep the local state
  ensure_git_status_clean
  ensure_git_branch(branch: "master")
  git_pull

  # regen the changelog and open it
  sh "cd .. && github_changelog_generator -t $GITHUB_TOKEN && subl CHANGELOG.md"

  # ask for the version
  title = prompt(text: 'Release Title: ')
  description = prompt(text: "Release changelog: ",
   multi_line_end_keyword: "END")

  # create a new release on GitHub
  repo_url = "czechboy0/Buildasaur"
  ENV["FL_GITHUB_RELEASE_API_TOKEN"] = ENV["GITHUB_TOKEN"]
  release = set_github_release(
    repository_name: repo_url,
    upload_assets: assets,
    name: [version_tag, title].join(" - "),
    tag_name: version_tag,
    description: description,
    is_draft: false,
    is_prerelease: false
  )

  sh "cd .. && rm -rf build" #delete built ipa/app

  # regenerate changelog to get it committed
  sh "cd .. && github_changelog_generator -t $GITHUB_TOKEN"
  sh "cd .. && git commit -am \"changelog\" && git push"

  # notify us on slack
  slack(
    slack_url: ENV['SLACK_RELEASES_URL'],
    message: "Successfully released [Buildasaur #{version_tag}](#{release['html_url']}) :rocket:",
    payload: {
      "New" => release['body']
    }
  )

end

